# Generated by Django 3.2.5 on 2021-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211006_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='satuts',
            field=models.BooleanField(default=False),
        ),
    ]
